### ISSUE TITLE
Breaking changes proposal

### ISSUE THREAD

**Issue by ejmahler** [awelkie/RustFFT#13]
Hello, after my latest PR is merged in, we have the opportunity to make some breaking changes. I'm not sure what the best way forward is and so I'd like to talk about them.

- You suggested making individual algorithms available publically. I fully support this. In particular, if a user knows for sure their their input is a power of two, they can use the `Radix4` struct directly and avoid a trait object.

I don't see a problem with making every algorithm publically available. We will have to do a pass to make sure all of the interfaces into each algorithm is strong. This is almost the case now -- all algorithms' `process()` methods assert the size of the input and output slices, and most algorithms do an assert in the new() method as well. There are just a few, like radix4, that don't do any assertions when creating a new instance, and we should fix this.

- I was thinking that, if we do assertions on the input size in every algorithms' process() method, the `FFT` struct is now superfluous. What if we got rid if it? Then, rename the `FFTAlgorithm` trait to just `FFT`.

Then, the intended use of the API is for the user to make a new `Planner` instance, then call `plan_fft` directly.

IE, a user of RustFFT might type
```rust
use rustfft::(Planner, FFT};
use std::rc::Rc;

let mut planner = Planner::new(false);
let fft: Rc<FFT> = planner.plan_fft(1234);

fft.process(&mut input, &mut output);
```
I don't know how this affects the open issue to allow real-valued FFTs. One benefit of the FFT struct is that creates a place where data transformations and cleanup can occur. If we get rid of it, we won't have that benefit. What do you think?

One of the main reasons I like this change is that it makes FFT instances immutable, which looks nice ergonomically, and makes any code using RustFFT more flexible because it doesn't have to worry about borrow checker issues etc.

- Move the dft() function in lib.rs to tests/accuracy.rs. If we're making all of the algorithms publically available, then we can rename the `DFTAlgorithm` struct to just `DFT`, and a user who wants to run a DFT directly can use an instance of this struct.

What do you think about these changes? Do you have any other ideas? Back in the summer it sounded like you had some breaking changes you wanted to make.

**Comment by ejmahler** [comment]
An advantage of the second change is that it makes it easier for users to work directly with algorithms like MixedRadix

Because you could type something like: 

```rust
let mixed_fft = MixedRadix::new(planner.plan_fft(321), planner.plan_fft(123));
```

Without it, if you decide you want to  construct a FFT plan yourself, you have to construct the *entire thing* yourself. This change would let users mixed auto-planned and manually-planned FFTs.

**Comment by awelkie** [comment]
I'm not sure what you mean about the FFT struct allowing for data transformations and cleanup. Couldn't that still happen with the structs that implement `FFT`? I don't see any reason to not just use the `Planner` API you're proposing.

**Comment by ejmahler** [comment]
Writing it in one place vs writing it everywhere.

Although, I suppose we could write it directly on the FFT trait.

**Comment by ejmahler** [comment]
Another proposal: Make FFTnum depend on num::float and num::traits::FloatConst

num::float because it'll let us make the twiddle factor computation simpler, since we don't have to do the FromPrimitive step, since Complex::from_polar can handle inputs of type Float.

It would be cool to support other numeric types, especially num's BigDecimal whenever they add it. But it almost certainly won't implement Copy, which we already require. Rewriting the library to do math on non-copy numeric types will be a *massive* overhaul, so we're not actually gaining much by not requiring it.

And theoretically, our current system will support integer inputs, but all the twiddle factors will be rounded to 1, 0, or -1 and we'll get a wrong result.

So there isn't a large benefit to not depending on Float.

And FloatConst because it'll get us pi() and sqrt(2) constants for T.

**Comment by awelkie** [comment]
I agree that support for integers and BigDecimal may not be worth it. But what about fixed point numbers? I could see that being useful, especially in an embedded context. I think a fixed-point implementation could implement `FloatConst`, but probably not `num::Float`.

I think depending on `FloatConst` makes sense. But I would like to avoid requiring `Float` unless it makes things significantly simplier. To me, the current `FFTnum` isn't too much of a burden to make requiring `Float` worth it.

**Comment by ejmahler** [comment]
Hmm.

The primary benefit I was picturing of having pi() as a constant is that we could avoid the FromPrimitive step in the the twiddle factor generation. But I agree with your desire to avoid the float trait, and we would also need the float trait for that to work. so the only constant we would use is sqrt(2). At that point we may as well add neither trait and just add a SQRT_2 method to FFTnum

**Comment by awelkie** [comment]
Yeah, I would be fine with either using `FloatConst` for the sqrt(2) or just adding a sqrt_2() method to the `FFTnum` trait.

Where do we use the sqrt(2) constant? If it's just in the twiddle factor generation, then I would be fine with just using a `FromPrimitive::from_f64(2f64.sqrt())`. It may be a little more overhead, but if it's not in the actually FFT then I think that's fine.

**Comment by ejmahler** [comment]
The size 8 and 16 butterflies have to store it internally as a twiddle factor. It would be nice if only the "rader's algorithm" butterflies had to store any data besides a bool for the inverse. But not essential.
