### ISSUE TITLE
Use a more conventional way to capitalize letters in `FFTplanner`

### ISSUE THREAD

**Issue by Limeth** [awelkie/RustFFT#24]
Hello,
I think it would be a good idea to stick to the conventions widely used by the Rust community and capitalize the `P` in `FFTplanner`.

**Comment by ejmahler** [comment]
This would be a breaking change, so sadly it will have to wait for a 3.0 release. We just released 2.0 a couple months ago, and there aren't any other breaking changes on the horizon, so it may take a long time.

**Comment by mitchmindtree** [comment]
Just for the record, I think the more conventional rust would be `FftPlanner` (see the comment about acronyms under [this table](https://aturon.github.io/style/naming.html#general-conventions)).

**Comment by Limeth** [comment]
@mitchmindtree Good find! I changed the issue label accordingly.

**Comment by ejmahler** [comment]
Fixed in RustFFT 5.0. Thanks for being patient, everyone :)

By the way, all development from now on will be happening in https://github.com/ejmahler/RustFFT
