### ISSUE TITLE
Document the normalization used

### ISSUE THREAD

**Issue by cbourjau** [awelkie/RustFFT#25]
This library seems to be a good fit for my use case - thanks a lot for the hard work! I am having trouble finding the exact normalization it is using, though. Maybe I am overlooking it somewhere, but even if, maybe it would be worth a thought putting this information to a more obvious point in the docs? Also, am not quite sure which index of the output array corresponds to which Fourier coefficient. Might it be possible to add this information somewhere?

**Comment by ejmahler** [comment]
RustFFT computes results equivalent to the following formula (from wikipedia):

![RustFFT's FFT formula](https://wikimedia.org/api/rest_v1/media/math/render/svg/906443f96240974a5e678ad3f2d27dfe856d93bb)

You can find a dead simple implementation of this, used for testing purposes, in the DFT module: https://github.com/awelkie/RustFFT/blob/master/src/algorithm/dft.rs#L98

To answer your normalization question, using this formula means we don't perform any normalization. If you compute the FFT of an array, then compute the inverse FFT on the result, your final output will be your original array scaled by n/2, so scale the result by 2/n to get your original data back. (I agree that this should be documented)

To answer your question about fourier coefficient, I' not too knowledgeable in this subject, but whichever coefficient is which in the O(n^2 ) formula above is the same coefficient in RustFFT's output.

**Comment by awelkie** [comment]
The output array goes from the lowest frequency (DC) at index 0 to the highest frequency (equivalently the least negative frequency) at the last index. In other words, it's in-order and not "fft shifted."

**Comment by cbourjau** [comment]
Thanks a lot to both of you for this clarification and this library!

**Comment by ejmahler** [comment]
Closed by #52
