### ISSUE TITLE
Better KissFFT benchmarking

### ISSUE THREAD

**Issue by awelkie** [awelkie/RustFFT#3]
The KissFFT Rust library that the benchmarking code depends on does not compile with optimizations, so the benchmarks aren't very valid.

The KissFFT library should build with optimizations, or (better yet) the benchmarking code should just link against KissFFT, and the user can build KissFFT however they like.

**Comment by m13253** [comment]
I am the author if KissFFT binding.

I just added `-O3` in `build.rs`.
Maybe there is a better solution (manual linking or gcc crate or something), but I will just wait and see if it suits.

And thank you.

**Comment by awelkie** [comment]
Awesome, thanks! I think the best solution is to use the `links` keyword in your manifest, and to use the `gcc` crate. This will let users control the optimization level and compiler when building KissFFT, or let them link against their own binaries. But since Cargo doesn't actually pass the compiler options down to the build script yet, and your build script already handles most of this functionality, this is the better solution for now.

This solves the biggest issue with benchmarking, so I'll mark this issue as solved.
