### ISSUE TITLE
Can multidimensional FFT be performed?

### ISSUE THREAD

**Issue by astrojhgu** [awelkie/RustFFT#39]
Or would it be supported in the future?

Thanks.

**Comment by ejmahler** [comment]
You can compute a multidimensional FFT, but you’ll have to do it manually.
There is no library support for it. A 2D FFT should be easy, make a FFT
instance for the size of each axis, and an array with width * height
elements. Iterate over your array in chunks of size width, and compute your
width-size FFT on each chunk. Then transpose your 2D array, and iterate
again in chunks of size height and compute your height-size FFT on each
chunk. After that, you probably want to transpose again.

The same idea is true for higher dimensions, with one FFT pass per
dimension.

Take a look at algorithm/mixed_radix.rs it does almost this exact “iterate
and transpose” algorithm, although it does a little extra work that you
won’t need

**Comment by jimrybarski** [comment]
Yes, the [ofuton](https://github.com/totem3/ofuton) crate uses rustfft to provide N-dimensional FFT.

**Comment by astrojhgu** [comment]
Thanks @ejmahler and @jimrybarski .
