### ISSUE TITLE
Discrete Cosine Transform

### ISSUE THREAD

**Issue by xd009642** [awelkie/RustFFT#45]
So I know the name is RustFFT, but is there any interest in adding a discrete cosine transform as it's equivalent to the FFT of a signal if it is doubled in length so it's evenly symmetrical?

**Comment by ejmahler** [comment]
Take a look at the crate “rustdct” which uses rust FFT as a backing
implementation

**Comment by xd009642** [comment]
Thanks that looks like what I want! I'll close this issue :+1:
