### ISSUE TITLE
Allow for inverse FFT

### ISSUE THREAD

**Issue by awelkie** [awelkie/RustFFT#5]

**Comment by itdaniher** [comment]
What're your thoughts on an API for this? 

``` rust
impl FFT {
    pub fn new(len: usize, forward: bool) -> Self { } 
}
```

And having a line like

``` rust
signal = signal.iter().map(|x|x.conj()).collect();
```

enabled in the subsequent call to process by the 'forward' flag might be a trivial path forward.

**Comment by itdaniher** [comment]
A fairly specialized but rather convenient abstraction I've used over kissfft in the past can be found at https://github.com/ade-ma/LibRedio/blob/master/src/kissfft/src/kissfft.rs#L18.

**Comment by awelkie** [comment]
I think your API is fine, and your idea of simply conjugating the signal based on the inverse flag is a good way to get it working fast. I think I'll do this today so I can solidify the API.

But the real way to do this is to calculate the twiddle factors (roots of unity) differently based on whether you want a forward or inverse FFT. And I think there's a small change that needs to be made to the length 4 butterfly function to handle inverse FFTs. This should give a speedup over conjugating the signal, although I'm not sure how much.

Thanks for the suggestion.
