### ISSUE TITLE
Fix bare_trait_objects warning

### ISSUE THREAD

**Issue by jrebelo** [awelkie/RustFFT#51]
When compiling the crate with rustc 1.39.0 there appear quite a few warning: trait objects without an explicit `dyn` are deprecated. It should be a very trivial fix without behavioural changes so I like to suggest fixing those to make the build a bit cleaner.

**Comment by ejmahler** [comment]
I would like to address this.

We can't add the dyn keyword, as that was added in rustc 1.27, and rustfft supports rustc 1.26.

But there must be some way to suppress this warning?

**Comment by jrebelo** [comment]
I guess you could silence the warnings by adding #![allow(bare_trait_objects)] to lib.rs

Though I assume (I haven't checked for sure) that this might become an error in the future so the build might eventually break.

**Comment by ejmahler** [comment]
Even though this is staying a 2015 edition crate? That seems like the kind
of thing the edition system was specifically designed to avoid.

I will look into the allow thing, thanks for the suggestion

**Comment by jrebelo** [comment]
It is a good question with the edition. I am not sure about that but it would seem strange if this would break indeed.

**Comment by ejmahler** [comment]
Ok, #55 resolves this issue. I'll actually go through with closing it when I push a new version to crates.io, which I should be able to do tomorrow.

**Comment by ejmahler** [comment]
Fixed in rustfft 3.0.1
