### ISSUE TITLE
Bump num dependencies

### ISSUE THREAD

**Issue by osannolik** [awelkie/RustFFT#59]
Please consider updating version dependency of e.g. num-complex. I am using num-complex 0.3 and get compile errors like

```
27 |         input.as_slice_mut().unwrap(),
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `num_complex::Complex`, found a different struct `num_complex::Complex`
   |
   = note: expected mutable reference `&mut [num_complex::Complex<_>]`
              found mutable reference `&mut [num_complex::Complex<f32>]`
   = note: perhaps two different versions of crate `num_complex` are being used?
```

I could use the reexported num-complex via rustfft with some workarounds, but it would be much nicer if I could use the same version everywhere...

**Comment by dvtomas** [comment]
Yes please, same problem here

**Comment by dvtomas** [comment]
Any updates on this?

**Comment by ejmahler** [comment]
https://crates.io/crates/rustfft/4.0.0

**Comment by dvtomas** [comment]
Thank you!
