### ISSUE TITLE
submodule rust-kissfft hash doesn't resolve

### ISSUE THREAD

**Issue by itdaniher** [awelkie/RustFFT#6]
https://github.com/m13253/rust-kissfft/tree/51b7adf0bceaf77e51eff4e933053a1fa8ab0a5c 404's for me.

**Comment by awelkie** [comment]
Ah, it looks like I don't really know how git submodules work. I've got a bunch of local changes to the rust-kissfft repo on my machine, and I thought those would be pushed to this repo. It looks like I'll just have to hold a copy of `rust-kissfft` in my repo, and forget the whole submodule thing.

**Comment by itdaniher** [comment]
Or fork rust-kissfft, push your changes there, and add that as a submodule.

**Comment by awelkie** [comment]
Done.
